name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    
    - name: Find and Replace
      run: ((Get-Content -path seeder-app-C-sharp\Jwt.cs -Raw) -replace 'SUPERSECRETPLACEHOLDER','${{ secrets.JwtToken }}') | Set-Content -Path seeder-app-C-sharp\Jwt.cs
        
    - name: setup MS-build
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.7

    - name: Restore nuget packages
      run: nuget restore seeder-app-C-sharp.sln
    
    - name: Build
      run: msbuild seeder-app-C-sharp.sln /p:Configuration=Release /p:Platform=x64
      
    - name: Create folder
      run: |
          copy seeder-app-C-sharp\bin\x64\Release\seeder-app-C-sharp.exe build
          
    - name: Deploy 🚀 # deploy to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: community-network/bf1-seeder
          publish_branch: main # default: gh-pages
          publish_dir: build
          enable_jekyll: true
